name: build and test SUEWS

on: [push]

jobs:
  build_test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]


    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: 'yes'
        token: ${{ secrets.GITHUB_TOKEN }}
    # - name: test
    #   run: ls -l
    # - name: show
    #   run: ls -lrt .
    # - name: show
    #   run: ls -lrt WRF
    # - name: show
    #   run: ls -lrt SUEWS

#     - name: Github Hub
#       uses: elgohr/Github-Hub-Action@1.2
#       env:
#         GITHUB_TOKEN: ${{ secrets.GH_PAT }}
#       with:
#         args: submodule update
    # - name: Checkout submodules
    #   uses: textbook/git-checkout-submodule-action@2.0.0
    # - name: install
    #   run: sudo apt-get install graphviz doxygen-gui
    # - name: Build Doxygen pages
    #   run: |
    #    cd docs
    #    ./deploy-doxygen-gh-pages.sh
    # - name: Deploy to GitHub Pages
    #   uses: JamesIves/github-pages-deploy-action@1.1.3
    #   env:
    #    FOLDER: docs/doxygenoutput/html
    #    BRANCH: gh-pages
    #    BUILD_SCRIPT: apt-get install -y graphviz doxygen-gui; cd docs; doxygen; cd ..
    #    ACCESS_TOKEN: ${{ secrets.GH_PAT }}
